const DEX='https://api.dexscreener.com';
const BIRD='https://public-api.birdeye.so';
async function get(url,opts={}){const r=await fetch(url,{...opts,headers:{accept:'application/json',...(opts.headers||{})}});if(!r.ok)throw new Error(`${r.status} ${url}`);return r.json()}
const num=(x,d=0)=>Number.isFinite(Number(x))?Number(x):d;
const money=n=>n>=1e6?`$${(n/1e6).toFixed(2)}M`:n>=1e3?`$${(n/1e3).toFixed(1)}K`:`$${n.toFixed(0)}`;
const clamp=n=>Math.max(0,Math.min(100,Math.round(n)));
function score(p,smart,holder){const liq=num(p.liquidity?.usd),mc=num(p.marketCap||p.fdv),vol=num(p.volume?.h24),buys=num(p.txns?.h1?.buys),sells=num(p.txns?.h1?.sells),ageMin=Math.max(1,(Date.now()-num(p.pairCreatedAt,Date.now()))/60000);let demand=50+Math.min(35,buys*2)-Math.min(25,sells);if(vol>mc*.5)demand+=10;demand=clamp(demand);let safety=50+(liq>mc*.15?18:0)+(liq>25000?12:0)-(liq<10000?25:0);safety-=holder?.badSupply>10?25:holder?.badSupply>5?12:0;safety=clamp(safety);let thesis=p.info?75:45;let setup=clamp((demand+safety+(smart?.score||0))/3);let total=Math.round(thesis*.18+demand*.24+(smart?.score||0)*.22+safety*.2+setup*.16);let early=mc<250000&&ageMin<1440;let verdict=(smart?.verified&&smart.score>=65&&total>=78&&safety>=65&&demand>=65)?'gem':total>=55?'watch':'pass';return {thesis,demand,smart:smart?.score||0,safety,setup,score:total,verdict,early}}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');let sources={dex:false,birdeye:false,smart:false,holder:false,fresh:false};try{
const profiles=await get(`${DEX}/token-profiles/latest/v1`);sources.dex=true;const arr=(Array.isArray(profiles)?profiles:profiles?.data||[]).filter(x=>x.chainId==='solana'&&x.tokenAddress).slice(0,30);
const results=await Promise.all(arr.map(async x=>{try{const pd=await get(`${DEX}/token-pairs/v1/solana/${x.tokenAddress}`);const pairs=Array.isArray(pd)?pd:pd?.pairs||[];const best=pairs.filter(p=>p.dexId).sort((a,b)=>num(b.liquidity?.usd)-num(a.liquidity?.usd))[0];if(!best)return null;const mc=num(best.marketCap||best.fdv);if(mc<50000||mc>5000000||num(best.liquidity?.usd)<5000)return null;return {...best,profile:x}}catch{return null}}));
const rows=results.filter(Boolean);const key=process.env.BIRDEYE_API_KEY;
if(key){sources.birdeye=true;try{const sm=await get(`${BIRD}/smart-money/v1/token/list?interval=1d&trader_style=all&sort_by=net_flow&sort_type=desc&offset=0&limit=50`,{headers:{'X-API-KEY':key,'x-chain':'solana'}});sources.smart=!!sm;const map=new Map((sm?.data?.items||[]).map(x=>[(x.address||x.token_address||'').toLowerCase(),x]));for(const p of rows){const x=map.get((p.baseToken?.address||'').toLowerCase());p._smart=x?{verified:true,score:clamp(60+Math.min(30,num(x.smart_traders_no||x.smartTradersNo)*4)+(num(x.net_flow||x.netFlow)>0?10:0)),summary:`Smart-money discovery hit${x.smart_traders_no?` • ${x.smart_traders_no} tracked smart trader(s)`:''}${x.net_flow?` • net flow ${money(Math.abs(num(x.net_flow)))}`:''}`}:{verified:false,score:0}}}catch{sources.smart=false}}
const coins=rows.map((p,i)=>{const s=score(p,p._smart,null),mc=num(p.marketCap||p.fdv),created=num(p.pairCreatedAt,Date.now()),ageMin=Math.max(1,(Date.now()-created)/60000),age=ageMin<60?`${Math.round(ageMin)}m`:ageMin<1440?`${Math.round(ageMin/60)}h`:`${Math.round(ageMin/1440)}d`;return {id:p.baseToken.address||String(i),address:p.baseToken.address,s:p.baseToken.symbol||'?',name:p.baseToken.name||'Unknown',mc,liq:num(p.liquidity?.usd),age,stage:mc<250000?'early':mc<1000000?'developing':'expansion',narrative:p.profile?.description||'Market signal detected',thesis:s.thesis,demand:s.demand,smart:s.smart,safety:s.safety,setup:s.setup,score:s.score,verdict:s.verdict,why:p.profile?.description||`Demand ${s.demand}/100 with ${money(num(p.volume?.h24))} 24h volume.`,catalyst:`${money(num(p.volume?.h1))} 1h volume • ${num(p.txns?.h1?.buys)} buys / ${num(p.txns?.h1?.sells)} sells`,decision:s.verdict==='gem'?'Investigate now — verify thesis, smart-money and holder risk before entry.':s.verdict==='watch'?'Watch — wait for confirmation; do not chase.':'Pass — current evidence does not clear the bar.',invalid:'Lose the thesis or demand structure; reassess after a material liquidity/price deterioration.',intel:p._smart||{verified:false},watch:false,url:p.url||`https://dexscreener.com/solana/${p.baseToken.address}`}});sources.fresh=true;return res.status(200).json({ok:true,generatedAt:new Date().toISOString(),sources,coins})
}catch(e){return res.status(502).json({ok:false,error:e.message,sources,coins:[]})}}
